# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: vitorbenedito/golang-nodejs:0.1
pipelines:
  default:
    - step:
        name: tests
        script: # Modify the commands below to build your repository.
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_FULL_NAME}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}/api"
          - go mod vendor
          - go build -v
          - go test -v
        services:
          - docker
        caches:
          - docker
          - gomodules
    - step:
        name: deploy
        script: # Modify the commands below to build your repository.
          - ls
          - go mod vendor
          - apt-get -y install zip
          - make clean build
          - npm install -g serverless
          - npm install -g serverless-domain-manager
          - serverless config credentials --stage dev --provider aws --key ${aws_secret_access_key} --secret ${aws_access_key_id}
          - serverless deploy --force --verbose --stage dev
        services:
          - docker
        caches:
          - docker
          - gomodules
          - node
definitions:
  caches:
    gomodules: vendor