version: '3.1'

services:
 db:
  image: postgres
  container_name: postgres_cardappin
  restart: always
  ports:
   - 5433:5432
  environment:
   - POSTGRES_USER=test
   - POSTGRES_PASSWORD=test
   - POSTGRES_DB=cardappin


